language: node_js
services:
  - mongodb
before_install:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"ngudbhav",pwd:"ngudbhav",roles:["readWrite"]});'
  - npm install mongoose
before_script:
  - sleep 15
node_js:
  - "8"